### PR TITLE
Updates and clarifications to Readme + Offline app

### PR DESCRIPTION
**Pull request by ramezrafla**

### CODE REVIEW

**Comment by ramezrafla** [comment]
Please ignore the last commit (still working on some edge cases bugs)

**Comment by ilan-schemoul** [comment]
Interesting PR, thanks for your participation. Pertinent information have been added to the Readme.
Tough returning HTML is going to cause problems (see comments above).

**Comment by ilan-schemoul** [comment]
Okay so I'm just going to take the changes made to the readme.md as you still didn't fix the sw.js

**Comment by ramezrafla** [comment]
I am not sure I understand, I am looking at this thread and there is nothing to comment on. What you can do is take what you like from the PR and leave the rest out. Specifically, I am working on sw.js itself. But the readme can use the changes I propose.

**Comment by ilan-schemoul** [comment]
Okay I taught you wanted me to wait you to update the SW.js before doing anything about this PR.

**Comment by ilan-schemoul** [comment]
Okay I'm going to not merge this PR but just make the needed changes on my local Readme.md then `push` it. I'm not used to solve PR conflicts so I'm just gonna mess up everything.

**Comment by ilan-schemoul** [comment]
Sorry for the delay I taught for a moment that I've updated the repo already. 8690c887f0208b49bee25c4c616dd996794b7d54 is based on your update on the Readme.
Thanks for the contribution.

**Pull request closed without merging**
